---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana
  namespace: solace-monitoring
spec:
  url: https://grafana.github.io/helm-charts
  interval: 10m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: solace-monitoring
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 10m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jaegertracing
  namespace: solace-monitoring
spec:
  url: https://jaegertracing.github.io/helm-charts
  interval: 10m
