---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: pubsubplus
  namespace: solace-system
spec:
  url: https://solaceproducts.github.io/pubsubplus-kubernetes-quickstart/helm-charts
  interval: 10m

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pubsubplus
spec:
  releaseName: pubsubplus
  interval: 1m
  chart:
    spec:
      chart: pubsubplus
      version: "3.1.0"
      sourceRef:
        kind: HelmRepository
        name: pubsubplus
        namespace: solace-system
  values:
    image:
      repository: solace/solace-pubsub-standard
      tag: latest
    solace:
      redundancy: true
      podModifierEnabled: true
      size: dev
    storage:
      size: 10Gi