---
apiVersion: v1
kind: Service
metadata:
 labels:
   app: solace-prometheus-exporter
 name: solace-prometheus-exporter
spec:
 ports:
   - name: 'http'
     port: 9628
     targetPort: 9628
 selector:
   app: solace-prometheus-exporter
 type: ClusterIP